name: 4get
services:
  4get:
    container_name: 4get
    image: luuul/4get:latest
    restart: unless-stopped
    ports:
      - 4030:80
    volumes:
      - /DATA/AppData/$AppID/config:/var/www/html/config

x-casaos:
  architectures:
    - amd64
    - arm64
  main: 4get
  title:
    en_us: 4get
  tagline:
    en_us: A lightweight, privacy-focused meta-search engine.
  description:
    en_us: 4get is a minimalist search engine that aggregates results from multiple providers without tracking your activity. It offers a clean, ad-free interface and respects user privacy.
  developer: 4get
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/4get.png
  category: Charlie
  port_map: "4030"
