name: libreddit
services:
  libreddit:
    container_name: libreddit
    image: spikecodes/libreddit:latest
    restart: unless-stopped
    ports:
      - 4030:8080
    environment:
      - LIBREDDIT_DEFAULT_THEME=ocean
      - LIBREDDIT_DARK_MODE=on
    volumes:
      - /DATA/AppData/$AppID/data:/data

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm/v7
  main: libreddit
  title:
    en_us: Libreddit
  tagline:
    en_us: A private front-end for Reddit.
  description:
    en_us: Libreddit is a private front-end for Reddit, designed to provide a better browsing experience without tracking and with a clean, fast interface.
  developer: SpikeCodes
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/libreddit.png
  category: Charlie
  port_map: "4030"
